services:
  app:
    build:
      context: .
      args:
        APP_BASE_PATH: ${APP_BASE_PATH}
    container_name: dasarang-class
    restart: always
    ports:
      - "3100:3100"
    env_file:
      - .env
